import json
import os

nb = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Cuarta Iteración: Arquitectura Avanzada en PyTorch (Gating Network + Focal Loss)\n",
    "\n",
    "### Los 2 Avances Científicos Implementados Aquí:\n",
    "\n",
    "**1. Mecanismo de Apagado Dinámico (Gating / Atención):**\n",
    "Hemos construido una red neuronal personalizada que tiene un \"Juez\". Este juez analiza las variables originales del cliente y emite un voto de confianza (entre 0 y 1) para LightGBM y CatBoost. Si el Juez detecta que el cliente pertenece a un segmento donde los árboles suelen fallar, multiplica la predicción del árbol por 0.01 (apagándola casi por completo) y le da toda la voz a la Red Neuronal profunda.\n",
    "\n",
    "**2. Aproximación a Optimización de AUC (Focal Loss):**\n",
    "El AUC es una métrica de \"Rankeo\" (función escalonada) y por tanto no tiene derivada matemática. Para lograr que la red aprenda algo similar al AUC (que priorice la minoría difícil y margine a la mayoría fácil), reemplazamos la pérdida clásica por **Focal Loss**. Focal Loss aniquila matemáticamente la influencia de los clientes fáciles (el 85% de clase 0) y concentra casi todo el descenso de gradiente en los clientes difíciles que los árboles no pudieron predecir bien."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import warnings\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import lightgbm as lgb\n",
    "from catboost import CatBoostClassifier, Pool\n",
    "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.model_selection import StratifiedKFold, train_test_split\n",
    "from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "print(\"✅ Librerías de PyTorch e IA Clásica importadas.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. CARGA Y PARTICIÓN DEL DATASET (Igual que en la Fase 3)\n",
    "train_df = pd.read_csv('../../dataset/train.csv')\n",
    "\n",
    "X = train_df.drop(['id_cliente', 'objetivo'], axis=1)\n",
    "y = train_df['objetivo']\n",
    "\n",
    "X_train_full, X_test_final, y_train_full, y_test_final = train_test_split(\n",
    "    X, y, test_size=0.10, stratify=y, random_state=42\n",
    ")\n",
    "\n",
    "cat_cols = ['ocupacion', 'region', 'canal_adquisicion', 'banda_riesgo', 'dispositivo_principal']\n",
    "num_cols = [c for c in X.columns if c not in cat_cols]\n",
    "\n",
    "X_train_cb = X_train_full.copy()\n",
    "X_test_cb = X_test_final.copy()\n",
    "for col in cat_cols:\n",
    "    X_train_cb[col] = X_train_cb[col].astype(str)\n",
    "    X_test_cb[col] = X_test_cb[col].astype(str)\n",
    "    X_train_full[col] = X_train_full[col].astype('category')\n",
    "    X_test_final[col] = X_test_final[col].astype('category')\n",
    "\n",
    "print(\"✅ Datos divididos y categorías ajustadas.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 2. GENERACIÓN DE PREDICCIONES OOF DE ÁRBOLES EXPERTOS\n",
    "skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
    "\n",
    "oof_lgb = np.zeros(len(X_train_full))\n",
    "test_preds_lgb = np.zeros(len(X_test_final))\n",
    "oof_cb = np.zeros(len(X_train_full))\n",
    "test_preds_cb = np.zeros(len(X_test_final))\n",
    "\n",
    "best_lgb_params = {'num_leaves': 42, 'learning_rate': 0.017766463699737917, 'min_child_samples': 44, 'subsample': 0.6548629928035845, 'colsample_bytree': 0.595372408030665, 'reg_alpha': 4.9893861303564696e-05, 'reg_lambda': 0.1440126277634314}\n",
    "\n",
    "print(\"🌳 Entrenando Expertos Base (LightGBM y CatBoost)...\")\n",
    "for fold, (train_idx, val_idx) in enumerate(skf.split(X_train_full, y_train_full)):\n",
    "    # LightGBM\n",
    "    model_lgb = lgb.LGBMClassifier(objective='binary', metric='auc', n_estimators=1000, random_state=42, verbose=-1, **best_lgb_params)\n",
    "    model_lgb.fit(X_train_full.iloc[train_idx], y_train_full.iloc[train_idx], \n",
    "                  eval_set=[(X_train_full.iloc[val_idx], y_train_full.iloc[val_idx])], callbacks=[lgb.early_stopping(30, verbose=False)])\n",
    "    oof_lgb[val_idx] = model_lgb.predict_proba(X_train_full.iloc[val_idx])[:, 1]\n",
    "    test_preds_lgb += model_lgb.predict_proba(X_test_final)[:, 1] / skf.n_splits\n",
    "    \n",
    "    # CatBoost\n",
    "    model_cb = CatBoostClassifier(eval_metric='AUC', random_seed=42, early_stopping_rounds=30, verbose=False, thread_count=-1)\n",
    "    train_pool = Pool(X_train_cb.iloc[train_idx], y_train_full.iloc[train_idx], cat_features=cat_cols)\n",
    "    val_pool = Pool(X_train_cb.iloc[val_idx], y_train_full.iloc[val_idx], cat_features=cat_cols)\n",
    "    model_cb.fit(train_pool, eval_set=val_pool, use_best_model=True)\n",
    "    oof_cb[val_idx] = model_cb.predict_proba(val_pool)[:, 1]\n",
    "    test_preds_cb += model_cb.predict_proba(Pool(X_test_cb, cat_features=cat_cols))[:, 1] / skf.n_splits\n",
    "\n",
    "print(f\"✅ OOF LightGBM AUC: {roc_auc_score(y_train_full, oof_lgb):.5f}\")\n",
    "print(f\"✅ OOF CatBoost AUC: {roc_auc_score(y_train_full, oof_cb):.5f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3. PREPARACIÓN DE TENSORES PARA PYTORCH\n",
    "print(\"⚙️ Escalando datos para PyTorch...\")\n",
    "preprocessor = ColumnTransformer(\n",
    "    transformers=[\n",
    "        ('num', Pipeline([('imputer', SimpleImputer(strategy='median')), ('scaler', StandardScaler())]), num_cols),\n",
    "        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_cols)\n",
    "    ]\n",
    ")\n",
    "\n",
    "X_train_rn_base = preprocessor.fit_transform(X_train_full)\n",
    "X_test_rn_base = preprocessor.transform(X_test_final)\n",
    "\n",
    "# Juntamos matrices OOF\n",
    "train_tree_preds = np.column_stack([oof_lgb, oof_cb])\n",
    "test_tree_preds = np.column_stack([test_preds_lgb, test_preds_cb])\n",
    "\n",
    "# ---------------------------\n",
    "# Validación Interna Limpia\n",
    "# ---------------------------\n",
    "X_t_feat, X_v_feat, X_t_preds, X_v_preds, y_t, y_v = train_test_split(\n",
    "    X_train_rn_base, train_tree_preds, y_train_full.values, test_size=0.15, stratify=y_train_full.values, random_state=42\n",
    ")\n",
    "\n",
    "# Convertir a Tensores PyTorch\n",
    "tensor_X_t_feat = torch.tensor(X_t_feat, dtype=torch.float32)\n",
    "tensor_X_t_preds = torch.tensor(X_t_preds, dtype=torch.float32)\n",
    "tensor_y_t = torch.tensor(y_t, dtype=torch.float32).view(-1, 1)\n",
    "\n",
    "tensor_X_v_feat = torch.tensor(X_v_feat, dtype=torch.float32)\n",
    "tensor_X_v_preds = torch.tensor(X_v_preds, dtype=torch.float32)\n",
    "tensor_y_v = torch.tensor(y_v, dtype=torch.float32).view(-1, 1)\n",
    "\n",
    "tensor_X_test_feat = torch.tensor(X_test_rn_base, dtype=torch.float32)\n",
    "tensor_X_test_preds = torch.tensor(test_tree_preds, dtype=torch.float32)\n",
    "\n",
    "print(\"✅ Tensores generados.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4. LA ARQUITECTURA DE IA AVANZADA (Gating + Focal Loss)\n",
    "class DynamicGatingMetaLearner(nn.Module):\n",
    "    def __init__(self, num_features):\n",
    "        super().__init__()\n",
    "        \n",
    "        # 1. El \"Juez\": Decide cuánto confiar en LightGBM y CatBoost\n",
    "        self.gating_network = nn.Sequential(\n",
    "            nn.Linear(num_features, 32),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(32, 2), # 2 salidas (pesos de confianza para los 2 árboles)\n",
    "            nn.Sigmoid() # Fuerza a que la confianza sea entre 0 y 1\n",
    "        )\n",
    "        \n",
    "        # 2. La Red Principal: Analiza el cliente a profundidad\n",
    "        self.main_network = nn.Sequential(\n",
    "            nn.Linear(num_features, 256),\n",
    "            nn.BatchNorm1d(256),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(256, 128),\n",
    "            nn.BatchNorm1d(128),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(128, 64),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(64, 1),\n",
    "            nn.Sigmoid()\n",
    "        )\n",
    "        \n",
    "        # 3. Mezclador Final: Junta la opinión de los árboles (ya modulada) + opinión propia\n",
    "        self.final_mixer = nn.Linear(3, 1)\n",
    "        \n",
    "    def forward(self, x_features, tree_preds):\n",
    "        # El Juez evalúa las variables y emite sus votos de confianza\n",
    "        gating_weights = self.gating_network(x_features) \n",
    "        \n",
    "        # Apagado Dinámico (Atención): Multiplica predicciones de los árboles por la confianza\n",
    "        gated_tree_preds = tree_preds * gating_weights\n",
    "        \n",
    "        # La Red emite su propia probabilidad\n",
    "        nn_pred = self.main_network(x_features)\n",
    "        \n",
    "        # Mezcla final\n",
    "        combined = torch.cat([gated_tree_preds, nn_pred], dim=1)\n",
    "        return torch.sigmoid(self.final_mixer(combined))\n",
    "\n",
    "# Implementación de Focal Loss (Aproximación de Ranking/AUC)\n",
    "class FocalLoss(nn.Module):\n",
    "    def __init__(self, alpha=1, gamma=2):\n",
    "        super(FocalLoss, self).__init__()\n",
    "        self.alpha = alpha\n",
    "        self.gamma = gamma\n",
    "\n",
    "    def forward(self, inputs, targets):\n",
    "        bce_loss = F.binary_cross_entropy(inputs, targets, reduction='none')\n",
    "        pt = torch.exp(-bce_loss) \n",
    "        focal_loss = self.alpha * (1-pt)**self.gamma * bce_loss\n",
    "        return torch.mean(focal_loss)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 5. BUCLE DE ENTRENAMIENTO PERSONALIZADO CON EARLY STOPPING POR AUC\n",
    "num_features = tensor_X_t_feat.shape[1]\n",
    "model = DynamicGatingMetaLearner(num_features)\n",
    "optimizer = torch.optim.AdamW(model.parameters(), lr=0.001, weight_decay=1e-4)\n",
    "criterion = FocalLoss(gamma=2.0) # Forzamos a la red a enfocarse en los casos difíciles\n",
    "\n",
    "epochs = 300\n",
    "batch_size = 512\n",
    "best_auc = 0\n",
    "patience = 20\n",
    "patience_counter = 0\n",
    "best_model_weights = None\n",
    "\n",
    "print(\"🚀 Iniciando Entrenamiento PyTorch (Focal Loss + Gating + AUC Early Stopping)\")\n",
    "for epoch in range(epochs):\n",
    "    model.train()\n",
    "    permutation = torch.randperm(tensor_X_t_feat.size()[0])\n",
    "    \n",
    "    # Mini-batches\n",
    "    for i in range(0, tensor_X_t_feat.size()[0], batch_size):\n",
    "        indices = permutation[i:i+batch_size]\n",
    "        batch_x_feat, batch_x_preds, batch_y = tensor_X_t_feat[indices], tensor_X_t_preds[indices], tensor_y_t[indices]\n",
    "        \n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(batch_x_feat, batch_x_preds)\n",
    "        loss = criterion(outputs, batch_y)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "    # Evaluación por Época\n",
    "    model.eval()\n",
    "    with torch.no_grad():\n",
    "        val_outputs = model(tensor_X_v_feat, tensor_X_v_preds)\n",
    "        val_auc = roc_auc_score(tensor_y_v.numpy(), val_outputs.numpy())\n",
    "        \n",
    "        if val_auc > best_auc:\n",
    "            best_auc = val_auc\n",
    "            best_model_weights = model.state_dict().copy()\n",
    "            patience_counter = 0\n",
    "        else:\n",
    "            patience_counter += 1\n",
    "            \n",
    "    if (epoch+1) % 10 == 0:\n",
    "        print(f\"Época {epoch+1:03d} | AUC Validación Limpia: {val_auc:.5f} | Mejor AUC Histórico: {best_auc:.5f}\")\n",
    "        \n",
    "    if patience_counter >= patience:\n",
    "        print(f\"\\n🛑 Early Stopping en la época {epoch+1}. Restaurando el mejor cerebro (AUC={best_auc:.5f})\")\n",
    "        model.load_state_dict(best_model_weights)\n",
    "        break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 6. EVALUACIÓN FINAL SOBRE EL 10% TEST PURO\n",
    "model.eval()\n",
    "with torch.no_grad():\n",
    "    final_probs = model(tensor_X_test_feat, tensor_X_test_preds).numpy()\n",
    "\n",
    "# Como el AUC no depende del threshold, usamos el threshold óptimo para F1 si queremos matriz de confusión balanceada\n",
    "# Por simplicidad usamos 0.5 o el promedio de las probabilidades.\n",
    "threshold = np.percentile(final_probs, 85) # Ajustamos umbral al top 15% (distribución real de la clase 1)\n",
    "final_preds_bin = (final_probs >= threshold).astype(int)\n",
    "\n",
    "final_auc = roc_auc_score(y_test_final, final_probs)\n",
    "final_gini = 2.0 * final_auc - 1.0\n",
    "\n",
    "print(\"\\n=======================================================\")\n",
    "print(\"📊 RESULTADOS FINALES SOBRE EL SET DE PRUEBA (10% PURO)\")\n",
    "print(\"=======================================================\")\n",
    "print(f\"⭐ AUC FINAL:  {final_auc:.5f}\")\n",
    "print(f\"🏆 GINI FINAL: {final_gini:.5f}\\n\")\n",
    "print(\"📉 MATRIZ DE CONFUSIÓN (Threshold Ajustado):\")\n",
    "print(confusion_matrix(y_test_final, final_preds_bin))\n",
    "print(\"\\n📋 REPORTE DE CLASIFICACIÓN:\")\n",
    "print(classification_report(y_test_final, final_preds_bin))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (modelo-datafest-bcp)",
   "language": "python",
   "name": "modelo-datafest-bcp"
  },
  "language_info": {
   "name": "python",
   "version": "3.14.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

nb_path = '/Users/aron/githubRepo/modelo-datafest-bcp/test/fourthAttempt/Pipeline_PyTorch_MoE.ipynb'
with open(nb_path, 'w') as f:
    json.dump(nb, f, indent=1)

print(f"Notebook created successfully at {nb_path}")
