import json

nb = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Quinto Intento: Transformers para Datos Tabulares (Puro PyTorch)\n",
    "\n",
    "### La Arquitectura Propuesta: Tabular FT-Transformer (Feature Tokenizer Transformer)\n",
    "\n",
    "Acabas de sugerir el Santo Grial de las redes neuronales tabulares modernas.\n",
    "En lugar de usar un MLP clásico que mezcla todas las variables a la fuerza, vamos a usar un **Transformer con Self-Attention (Mecanismo de Auto-Atención)**.\n",
    "\n",
    "**¿Cómo funciona?**\n",
    "1. **Tokenización:** Toma cada variable del cliente (ej. Edad=25) y en lugar de tratarlo como un simple número, lo proyecta en un \"Token\" matemático (un vector de 16 dimensiones). Cada columna se convierte en una \"palabra\" dentro de la \"oración\" que describe al cliente.\n",
    "2. **Self-Attention:** El Transformer compara cada variable contra TODAS las demás variables simultáneamente. Así, si descubre que la variable `Saldo` solo importa si la variable `Edad` es mayor a 30, le dará prioridad (Atención) a esa combinación exacta.\n",
    "3. **Clasificación:** Tras procesar todas las relaciones de atención, la información se condensa y se pasa por un evaluador final que optimiza directamente para Focal Loss (AUC)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "# 🛡️ PARCHE ANTI-DEADLOCK PARA MAC\n",
    "os.environ['OMP_NUM_THREADS'] = '1'\n",
    "os.environ['MKL_NUM_THREADS'] = '1'\n",
    "\n",
    "import warnings\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "print(\"✅ Librerías de PyTorch listas.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. CARGA DE DATOS PUROS\n",
    "train_df = pd.read_csv('../../dataset/train.csv')\n",
    "\n",
    "X = train_df.drop(['id_cliente', 'objetivo'], axis=1)\n",
    "y = train_df['objetivo']\n",
    "\n",
    "# Separamos el 10% puro de prueba final\n",
    "X_train_full, X_test_final, y_train_full, y_test_final = train_test_split(\n",
    "    X, y, test_size=0.10, stratify=y, random_state=42\n",
    ")\n",
    "\n",
    "cat_cols = ['ocupacion', 'region', 'canal_adquisicion', 'banda_riesgo', 'dispositivo_principal']\n",
    "num_cols = [c for c in X.columns if c not in cat_cols]\n",
    "\n",
    "# Escalado Puro\n",
    "print(\"⚙️ Escalando datos para PyTorch...\")\n",
    "preprocessor = ColumnTransformer(\n",
    "    transformers=[\n",
    "        ('num', Pipeline([('imputer', SimpleImputer(strategy='median')), ('scaler', StandardScaler())]), num_cols),\n",
    "        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_cols)\n",
    "    ]\n",
    ")\n",
    "\n",
    "X_train_rn = preprocessor.fit_transform(X_train_full)\n",
    "X_test_rn = preprocessor.transform(X_test_final)\n",
    "\n",
    "# Separamos Validación Limpia Interna (15%)\n",
    "X_t_feat, X_v_feat, y_t, y_v = train_test_split(\n",
    "    X_train_rn, y_train_full.values, test_size=0.15, stratify=y_train_full.values, random_state=42\n",
    ")\n",
    "\n",
    "# Tensores PyTorch\n",
    "tensor_X_t = torch.tensor(X_t_feat, dtype=torch.float32)\n",
    "tensor_y_t = torch.tensor(y_t, dtype=torch.float32).view(-1, 1)\n",
    "tensor_X_v = torch.tensor(X_v_feat, dtype=torch.float32)\n",
    "tensor_y_v = torch.tensor(y_v, dtype=torch.float32).view(-1, 1)\n",
    "tensor_X_test = torch.tensor(X_test_rn, dtype=torch.float32)\n",
    "\n",
    "print(f\"✅ Tensores generados. Dimensiones de entrada: {tensor_X_t.shape[1]} columnas.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 2. LA ARQUITECTURA: TABULAR TRANSFORMER CON SELF-ATTENTION\n",
    "class TabularTransformer(nn.Module):\n",
    "    def __init__(self, num_features, d_model=16, nhead=4, num_layers=2):\n",
    "        super().__init__()\n",
    "        self.num_features = num_features\n",
    "        self.d_model = d_model\n",
    "        \n",
    "        # Feature Tokenizer: Expande CADA UNA de las 40 variables a un vector de 16 dimensiones\n",
    "        self.feature_tokenizer = nn.Linear(1, d_model)\n",
    "        \n",
    "        # Mecanismo de Atención (El núcleo del Transformer)\n",
    "        encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead, dim_feedforward=64, dropout=0.2, batch_first=True)\n",
    "        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)\n",
    "        \n",
    "        # Clasificador Final\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.Linear(num_features * d_model, 64),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(64, 1),\n",
    "            nn.Sigmoid()\n",
    "        )\n",
    "        \n",
    "    def forward(self, x):\n",
    "        # x viene con forma [batch_size, 40 variables]\n",
    "        # Le agregamos una dimensión extra para tratar cada variable como una unidad aislada [batch, 40, 1]\n",
    "        x_expanded = x.unsqueeze(2) \n",
    "        \n",
    "        # Pasa por el Tokenizer -> Forma: [batch, 40, d_model=16]\n",
    "        tokens = self.feature_tokenizer(x_expanded)\n",
    "        \n",
    "        # El Transformer aplica Self-Attention. Aquí descubre si Edad se relaciona con Saldo.\n",
    "        attended_tokens = self.transformer(tokens)\n",
    "        \n",
    "        # Aplanamos todas las variables atendidas para pasarlas al clasificador final\n",
    "        flattened = attended_tokens.reshape(x.size(0), -1)\n",
    "        \n",
    "        # Decisión Final\n",
    "        return self.classifier(flattened)\n",
    "\n",
    "class FocalLoss(nn.Module):\n",
    "    def __init__(self, alpha=1, gamma=2):\n",
    "        super(FocalLoss, self).__init__()\n",
    "        self.alpha = alpha\n",
    "        self.gamma = gamma\n",
    "\n",
    "    def forward(self, inputs, targets):\n",
    "        bce_loss = F.binary_cross_entropy(inputs, targets, reduction='none')\n",
    "        pt = torch.exp(-bce_loss) \n",
    "        focal_loss = self.alpha * (1-pt)**self.gamma * bce_loss\n",
    "        return torch.mean(focal_loss)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3. BUCLE DE ENTRENAMIENTO PURO (AUC EARLY STOPPING)\n",
    "num_features = tensor_X_t.shape[1]\n",
    "model = TabularTransformer(num_features=num_features, d_model=16, nhead=4, num_layers=2)\n",
    "optimizer = torch.optim.AdamW(model.parameters(), lr=0.001, weight_decay=1e-4)\n",
    "criterion = FocalLoss(gamma=2.0)\n",
    "\n",
    "epochs = 200\n",
    "batch_size = 512\n",
    "best_auc = 0\n",
    "patience = 20\n",
    "patience_counter = 0\n",
    "best_model_weights = None\n",
    "\n",
    "print(\"🚀 Iniciando Entrenamiento de TABULAR TRANSFORMER (Focal Loss + AUC Early Stopping)\")\n",
    "for epoch in range(epochs):\n",
    "    model.train()\n",
    "    permutation = torch.randperm(tensor_X_t.size()[0])\n",
    "    \n",
    "    for i in range(0, tensor_X_t.size()[0], batch_size):\n",
    "        indices = permutation[i:i+batch_size]\n",
    "        batch_x, batch_y = tensor_X_t[indices], tensor_y_t[indices]\n",
    "        \n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(batch_x)\n",
    "        loss = criterion(outputs, batch_y)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "    model.eval()\n",
    "    with torch.no_grad():\n",
    "        val_outputs = model(tensor_X_v)\n",
    "        val_auc = roc_auc_score(tensor_y_v.numpy(), val_outputs.numpy())\n",
    "        \n",
    "        if val_auc > best_auc:\n",
    "            best_auc = val_auc\n",
    "            best_model_weights = model.state_dict().copy()\n",
    "            patience_counter = 0\n",
    "        else:\n",
    "            patience_counter += 1\n",
    "            \n",
    "    if (epoch+1) % 5 == 0:\n",
    "        print(f\"Época {epoch+1:03d} | AUC Validación Limpia: {val_auc:.5f} | Mejor AUC Histórico: {best_auc:.5f}\")\n",
    "        \n",
    "    if patience_counter >= patience:\n",
    "        print(f\"\\n🛑 Early Stopping en la época {epoch+1}. Restaurando el mejor cerebro (AUC={best_auc:.5f})\")\n",
    "        model.load_state_dict(best_model_weights)\n",
    "        break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4. EVALUACIÓN FINAL TRANSFORMER SOBRE EL 10% TEST PURO\n",
    "model.eval()\n",
    "with torch.no_grad():\n",
    "    final_probs = model(tensor_X_test).numpy()\n",
    "\n",
    "threshold = np.percentile(final_probs, 85)\n",
    "final_preds_bin = (final_probs >= threshold).astype(int)\n",
    "\n",
    "final_auc = roc_auc_score(y_test_final, final_probs)\n",
    "final_gini = 2.0 * final_auc - 1.0\n",
    "\n",
    "print(\"\\n=======================================================\")\n",
    "print(\"📊 RESULTADOS FINALES TRANSFORMER SOBRE SET DE PRUEBA (10%)\")\n",
    "print(\"=======================================================\")\n",
    "print(f\"⭐ AUC FINAL:  {final_auc:.5f}\")\n",
    "print(f\"🏆 GINI FINAL: {final_gini:.5f}\\n\")\n",
    "print(\"📉 MATRIZ DE CONFUSIÓN (Threshold Ajustado):\")\n",
    "print(confusion_matrix(y_test_final, final_preds_bin))\n",
    "print(\"\\n📋 REPORTE DE CLASIFICACIÓN:\")\n",
    "print(classification_report(y_test_final, final_preds_bin))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (modelo-datafest-bcp)",
   "language": "python",
   "name": "modelo-datafest-bcp"
  },
  "language_info": {
   "name": "python",
   "version": "3.14.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

nb_path = '/Users/aron/githubRepo/modelo-datafest-bcp/test/fifthAttempt/Pipeline_Transformer.ipynb'
with open(nb_path, 'w') as f:
    json.dump(nb, f, indent=1)

print(f"Notebook created successfully at {nb_path}")
